export const APP_DATA = {
  meta: {
    lastVerified: "March 10, 2026",
  },
  filters: [
    { id: "all", label: "All tracks" },
    { id: "prevention", label: "Prevention" },
    { id: "digital", label: "Digital safety" },
    { id: "wellbeing", label: "Wellbeing" },
    { id: "response", label: "Reporting" },
    { id: "leadership", label: "Leadership" },
  ],
  tracks: [
    {
      id: "harassment-toolkit",
      category: "prevention",
      title: "Harassment prevention toolkit",
      duration: "90 minutes",
      audience: "Students, campuses, workplaces",
      format: "Guide plus scenarios",
      summary: "Recognize boundary violations early, document facts clearly, and choose safer intervention options.",
      tags: ["Prevention", "Campus", "Workplace"],
      roleTags: ["student", "educator", "workplace", "ngo"],
      goalTags: ["prevention", "response", "leadership"],
      outcomes: [
        "Differentiate unsafe behavior, coercion, retaliation, and abuse of power.",
        "Use a simple incident documentation checklist without escalating conflict.",
        "Map internal, community, and emergency escalation routes.",
      ],
      materials: [
        "Red-flag checklist",
        "Documentation template",
        "Scenario discussion prompts",
      ],
    },
    {
      id: "consent-boundaries",
      category: "prevention",
      title: "Consent and healthy boundaries",
      duration: "75 minutes",
      audience: "Students, parents, youth groups",
      format: "Micro-lessons plus reflection",
      summary: "Translate consent from theory into everyday communication, digital boundaries, and safer decision making.",
      tags: ["Consent", "Communication", "Youth"],
      roleTags: ["student", "parent", "educator"],
      goalTags: ["prevention", "wellbeing"],
      outcomes: [
        "Use plain language to explain consent, pressure, and revocable agreement.",
        "Recognize digital boundary violations, social pressure, and unsafe silence.",
        "Practice supportive responses when someone says no, pauses, or discloses harm.",
      ],
      materials: [
        "Boundary-setting prompts",
        "Healthy relationship indicators",
        "Facilitator opening script",
      ],
    },
    {
      id: "digital-defense",
      category: "digital",
      title: "Digital safety and scam defense",
      duration: "80 minutes",
      audience: "Students, families, communities",
      format: "Checklist plus action drills",
      summary: "Cover privacy hygiene, impersonation scams, account takeover risks, and immediate response steps for cyber abuse.",
      tags: ["Cyber", "Privacy", "Scam defense"],
      roleTags: ["student", "parent", "ngo", "workplace"],
      goalTags: ["digital", "response", "prevention"],
      outcomes: [
        "Spot common phishing, impersonation, sextortion, and social engineering patterns.",
        "Secure devices and accounts using repeatable privacy settings and credential habits.",
        "Use cybercrime reporting channels and preserve evidence responsibly.",
      ],
      materials: [
        "Account safety checklist",
        "Incident response worksheet",
        "Digital hygiene poster",
      ],
    },
    {
      id: "mental-health-response",
      category: "wellbeing",
      title: "Mental health first response",
      duration: "65 minutes",
      audience: "Educators, facilitators, peer leaders",
      format: "Support pathway brief",
      summary: "Teach first-response language, referral judgment, and what supportive listening looks like in non-clinical settings.",
      tags: ["Wellbeing", "Referral", "Peer support"],
      roleTags: ["educator", "ngo", "parent", "workplace"],
      goalTags: ["wellbeing", "response", "leadership"],
      outcomes: [
        "Use calm, non-judgmental phrases that reduce shame and panic.",
        "Separate urgent risk from ongoing support needs and referral needs.",
        "Guide someone toward mental health support without pretending to be a clinician.",
      ],
      materials: [
        "Support language guide",
        "Referral matrix",
        "Do-and-don't sheet",
      ],
    },
    {
      id: "reporting-referrals",
      category: "response",
      title: "Reporting, documentation, and referrals",
      duration: "70 minutes",
      audience: "Facilitators, HR teams, student leaders",
      format: "Operational playbook",
      summary: "Move from confusion to action with clear pathways for notes, evidence, referrals, escalation, and official reporting.",
      tags: ["Reporting", "Evidence", "Operations"],
      roleTags: ["educator", "ngo", "workplace", "student"],
      goalTags: ["response", "leadership"],
      outcomes: [
        "Create a minimal but useful incident record with dates, facts, and immediate safety concerns.",
        "Know when to use workplace channels, public reporting channels, or urgent emergency support.",
        "Reduce retraumatizing questions and duplicate storytelling where possible.",
      ],
      materials: [
        "Incident logging format",
        "Escalation checklist",
        "Referral directory template",
      ],
    },
    {
      id: "bystander-leadership",
      category: "leadership",
      title: "Bystander leadership and community safety",
      duration: "85 minutes",
      audience: "Clubs, NGOs, resident groups, workplaces",
      format: "Workshop module",
      summary: "Help participants intervene more safely, distribute responsibility, and build safety habits into group culture.",
      tags: ["Bystander", "Leadership", "Community"],
      roleTags: ["student", "ngo", "workplace", "educator"],
      goalTags: ["leadership", "prevention", "response"],
      outcomes: [
        "Choose between direct support, distraction, delegation, documentation, and delayed follow-up.",
        "Plan interventions according to personal safety, power dynamics, and urgency.",
        "Turn one-off awareness activity into a repeatable community safety norm.",
      ],
      materials: [
        "Intervention matrix",
        "Group charter prompt",
        "Workshop debrief guide",
      ],
    },
  ],
  supportNumbers: [
    {
      id: "112",
      number: "112",
      title: "Emergency Response Support System",
      description: "Use for immediate emergency help across police, fire, ambulance, and urgent public-safety response.",
      link: "https://112.gov.in/",
    },
    {
      id: "181",
      number: "181",
      title: "Women Helpline",
      description: "Widely used support route highlighted through Mission Shakti contact channels for women in distress.",
      link: "https://missionshakti.wcd.gov.in/contact",
    },
    {
      id: "1098",
      number: "1098",
      title: "CHILDLINE",
      description: "Emergency support number for children and minors who need protection, rescue, or assistance.",
      link: "https://missionshakti.wcd.gov.in/contact",
    },
    {
      id: "1930",
      number: "1930",
      title: "Cybercrime and urgent digital fraud support",
      description: "Use for cyber fraud response and to move quickly on digital financial crime reporting.",
      link: "https://cybercrime.gov.in/",
    },
    {
      id: "14416",
      number: "14416",
      title: "Tele-MANAS",
      description: "Mental health support pathway under the Ministry of Health and Family Welfare.",
      link: "https://telemanas.mohfw.gov.in/",
    },
    {
      id: "15100",
      number: "15100",
      title: "Legal aid support",
      description: "Legal support number referenced through Mission Shakti contact channels and public legal-aid pathways.",
      link: "https://missionshakti.wcd.gov.in/contact",
    },
  ],
  resources: [
    {
      id: "resource-112",
      title: "Emergency Response Support System",
      owner: "Government of India",
      description: "Official emergency platform covering core public-safety response pathways.",
      link: "https://112.gov.in/",
    },
    {
      id: "resource-mission-shakti",
      title: "Mission Shakti contact hub",
      owner: "Ministry of Women and Child Development",
      description: "Public contact and helpline information for women, children, cybercrime, mental health, and legal aid references.",
      link: "https://missionshakti.wcd.gov.in/contact",
    },
    {
      id: "resource-cybercrime",
      title: "National Cyber Crime Reporting Portal",
      owner: "Government of India",
      description: "Official reporting portal for cybercrime complaints and online abuse-related incidents.",
      link: "https://cybercrime.gov.in/",
    },
    {
      id: "resource-ncw",
      title: "National Commission for Women",
      owner: "NCW",
      description: "Public information, complaint pathways, and reference material related to women's rights and grievance channels.",
      link: "https://www.ncw.gov.in/",
    },
    {
      id: "resource-shebox",
      title: "SHe-Box",
      owner: "Ministry of Women and Child Development",
      description: "Sexual Harassment electronic reporting entry point for workplace complaint contexts.",
      link: "https://shebox.wcd.gov.in/",
    },
    {
      id: "resource-telemanas",
      title: "Tele-MANAS",
      owner: "Ministry of Health and Family Welfare",
      description: "Official mental health support resource and national access point.",
      link: "https://telemanas.mohfw.gov.in/",
    },
  ],
  programs: [
    {
      id: "campus-sprint",
      title: "Campus safety sprint",
      badge: "Quarterly cohort shell",
      summary: "A two-week implementation format for orientation teams, anti-ragging cells, and student welfare programs.",
      meta: ["2 weeks", "Hybrid", "Student-first"],
    },
    {
      id: "digital-trust-clinic",
      title: "Digital trust clinic",
      badge: "Repeatable workshop",
      summary: "A compact format for cyber hygiene, scam defense, and digital abuse reporting confidence in schools and communities.",
      meta: ["Half day", "Workshop", "Family-ready"],
    },
    {
      id: "facilitator-lab",
      title: "Community facilitator lab",
      badge: "Training-of-trainers shell",
      summary: "A field-friendly facilitator program for NGOs, counselors, and community champions who need structured delivery support.",
      meta: ["3 sessions", "Facilitated", "Scale-ready"],
    },
  ],
  standards: [
    {
      id: "structure",
      title: "Maintainable structure",
      description: "The project now uses separate HTML, CSS, JS, brand assets, docs, manifest, and service worker files.",
    },
    {
      id: "privacy",
      title: "Privacy-first interactions",
      description: "The old fake login flow has been removed. Planner preferences and progress stay in local storage only.",
    },
    {
      id: "credibility",
      title: "Higher-trust support data",
      description: "High-risk support references now point toward official or primary public-service sources instead of stale demo content.",
    },
    {
      id: "deployment",
      title: "Deployment readiness",
      description: "The site is installable, offline-friendly, responsive, and suitable for static hosting such as GitHub Pages.",
    },
  ],
};
